# Builds a .NET framework project
name: Nightly builds

env:
  # Project details
  projectName: OpenFK
  projectFolder: OpenFK
  solutionFile: OpenFK.sln

  # Repo details
  githubRepository: OpenFunk-mirror/OpenFunk
  mainBranchName: fix-ci

on:
  workflow_dispatch:
  
  push:
    branches-ignore:
      - "gh-pages"
  
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        platform: [ x64, x86 ]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v3

      - name: Install .NET Framework v4.5.2 SDK
        run: choco install netfx-4.5.2-devpack

      - name: Download Flash.OCX
        shell: cmd
        run: FetchBothOCXs.bat
      
      - name: Register Flash.OCX
        shell: cmd
        # The names of these .ocx files are important. They are copied over into the .exe.config file
        # Upon running the .exe, these filenames are referenced
        run: |
          "%systemroot%\System32\regsvr32.exe" /s "${{ github.workspace }}\Flash64.ocx"
          "%systemroot%\SysWow64\regsvr32.exe" /s "${{ github.workspace }}\Flash32.ocx"
      
      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}
      
      - name: Get version from update.xml
        id: getVersion
        uses: mavrosxristoforos/get-xml-info@2.1.0
        with:
          xml-file: update.xml
          xpath: //update/@version
      
      - name: Normalize the version string into SemVer format (x.x.x)
        id: normalizeVersion
        run: |
          $versionString = "${{ steps.getVersion.outputs.info }}"
          $digits = $versionString.Split(".").Length
          if ($digits -eq 1) { $versionString += ".0.0" }
          elseif ($digits -eq 2) { $versionString += ".0" }
          "VERSION=$($versionString)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - name: Set version in AssemblyInfo.cs
        uses: secondbounce/assemblyinfo-update@v2
        with:
          version: "${{ steps.normalizeVersion.outputs.VERSION }}"

      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:"${{ matrix.configuration == 'Release' && 'clean;' || '' }}rebuild" -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }} -verbosity:detailed
      
        # We delete the .ocx to avoid DMCAs on build artifacts (even though that's unlikely)
      - name: Remove .ocx files
        run: get-childitem -path "${{ env.projectFolder }}/bin/${{ matrix.platform }}/${{ matrix.configuration }}" -filter *.ocx | foreach-object { remove-item $_.fullname -force }

      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.platform }}/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.Nightly.${{ matrix.configuration }}.${{ matrix.platform }}
      
      - name: Put the build artifacts into an archive file
        run: Compress-Archive -Path "${{ env.projectFolder }}/bin/${{ matrix.platform }}/${{ matrix.configuration }}/*" -DestinationPath "${{ env.projectName }}.${{ matrix.configuration }}.${{ matrix.platform }}.zip"

      - name: Upload build result to the prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # assumes there already is an asset with the same name
        run: |
          gh release delete-asset nightly "${{ env.projectName }}.${{ matrix.configuration }}.${{ matrix.platform }}.zip" --yes
          gh release upload nightly "${{ env.projectName }}.${{ matrix.configuration }}.${{ matrix.platform }}.zip" --repo ${{ env.githubRepository }}


  finish:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set a bunch of variables
        id: info
        run: |
          $filesizes = gh release view --repo ${{ env.githubRepository }} nightly --json assets --jq '[ .assets[] | {name:.name, size:.size} | select(.name | startswith("${{ env.projectName }}")) | {(.name):.size} | to_entries ] | flatten | from_entries' | ConvertFrom-Json
          echo $filesizes
          "FILESIZE_RELEASE_64=$($filesizes.'${{ env.projectName }}.Release.x64.zip')" >> $env:GITHUB_OUTPUT
          "FILESIZE_RELEASE_86=$($filesizes.'${{ env.projectName }}.Release.x86.zip')" >> $env:GITHUB_OUTPUT
          "FILESIZE_DEBUG_64=$($filesizes.'${{ env.projectName }}.Debug.x64.zip')" >> $env:GITHUB_OUTPUT
          "FILESIZE_DEBUG_86=$($filesizes.'${{ env.projectName }}.Debug.x86.zip')" >> $env:GITHUB_OUTPUT

          "COMMIT_HASH=$(git log -1 --pretty=format:"%H")" >> $env:GITHUB_OUTPUT
          "SHORT_COMMIT_HASH=$(git log -1 --pretty=format:"%h")" >> $env:GITHUB_OUTPUT
          "LAST_COMMIT_TIMESTAMP=$(Get-Date -Date "$(git log -1 --pretty=format:'%aD')" -Format 'ddd, d MMM yyyy HH:mm:ss zzz')" >> $env:GITHUB_OUTPUT
          "BUILD_TIMESTAMP=$(Get-Date -Format "ddd, d MMM yyyy HH:mm:ss zzz")" >> $env:GITHUB_OUTPUT

      - name: Update update.xml and buld notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $content = @'
          <?xml version="1.0" encoding="utf-8"?>
          <update schema_version="2.0" id="openfunk" name="OpenFunk" version="${{ steps.info.outputs.COMMIT_HASH }}" version_name="OpenFunk@${{ steps.info.outputs.SHORT_COMMIT_HASH }}">
              <variant size="${{ steps.info.outputs.FILESIZE_RELEASE_64 }}" link="https://github.com/${{ env.githubRepository }}/releases/download/nightly/${{ env.projectName }}.Release.x64.zip">
                  <Property key="BuildConfiguration" value="Release" />
                  <Property key="Architecture" value="x64" />
              </variant>
              <variant size="${{ steps.info.outputs.FILESIZE_RELEASE_86 }}" link="https://github.com/${{ env.githubRepository }}/releases/download/nightly/${{ env.projectName }}.Release.x86.zip">
                  <Property key="BuildConfiguration" value="Release" />
                  <Property key="Architecture" value="x86" />
              </variant>
              <variant size="${{ steps.info.outputs.FILESIZE_DEBUG_64 }}" link="https://github.com/${{ env.githubRepository }}/releases/download/nightly/${{ env.projectName }}.Debug.x64.zip">
                  <Property key="BuildConfiguration" value="Debug" />
                  <Property key="Architecture" value="x64" />
              </variant>
              <variant size="${{ steps.info.outputs.FILESIZE_DEBUG_86 }}" link="https://github.com/${{ env.githubRepository }}/releases/download/nightly/${{ env.projectName }}.Debug.x86.zip">
                  <Property key="BuildConfiguration" value="Debug" />
                  <Property key="Architecture" value="x86" />
              </variant>
          </update>
          '@
          Set-Content -Path update.xml -Value $content -Encoding utf8
          # assumes there already is an update.xml
          gh release delete-asset nightly update.xml --yes
          gh release upload nightly update.xml --repo ${{ env.githubRepository }}

          @'
          Check the attached files for the latest nightly build.
          Note that the source code download and the tag are NOT kept up to date!

          Current build name: `${{ env.projectName }}@${{ steps.info.outputs.SHORT_COMMIT_HASH }}`
          Current version: `${{ steps.info.outputs.COMMIT_HASH }}`
          Last updated: `${{ steps.info.outputs.LAST_COMMIT_TIMESTAMP }}`
          Built at: `${{ steps.info.outputs.BUILD_TIMESTAMP }}`

          # Which file do I download?
          TLDR: try the `Release.x64` build. If that doesn't work, try `Release.x86`.

          The builds are distinguished by two properties: BuildConfiguration (Release/Debug) and Architecture (x64/x86).
          Unless you're planning to use a debugger program, you can disregard the Debug versions. It's a pretty obscure usecase anyway, but I aim to serve all of em :)
          For the architecture property, you can pick x64 99% of the time. The exceptions are when running a 32-bit operating system (usually only on very old computers) and in some cases when using wine.
          '@ | gh release edit nightly --notes-file -

# if there isn't a release on the nightly tag yet, create one(?)
# then edit it to include the new desc
# gh release view nightly --repo OpenFunk-mirror/FunkeySelectorGUI --json assets
# useful stuff right there

# epic game plan:
# - before building, ensure a release exists (nuh uh uh)
# - build and upload to release
# - update build info in release notes
# - update update.xml (requires filesize of all builds)
